stages:
  data_ingestion:
    cmd: python src/datas/data_ingestion.py

    deps:
    - data/external
    - src/datas/data_ingestion.py
    params:
    - Data_ingestion.test_size

    outs:
    - data/raw
  data_preprocessing:
    cmd: python src/datas/data_preprocessing.py
    deps:
    - data/raw
    - src/datas/data_preprocessing.py
    outs:
    - data/interim
    - models/scaler.pkl
  feature_engineering:
    cmd: python src/features/feature_engineering.py
    deps:
    - data/interim
    - src/features/feature_engineering.py
    outs:
    - data/processed
    - models/encoder.pkl
  model_building:
    cmd: python src/model/model_building.py
    deps:
    - data/processed
    - src/model/model_building.py
    params:
    - Model_building.n_estimator
    - Model_building.max_depth
    - Model_building.learning_rate
    outs:
    - models/model.pkl
  model_evaluation:
    cmd: python src/model/model_evaluation.py
    deps:
    - data/processed
    - models/model.pkl
    - src/model/model_building.py
    metrics:
    - reports/metrics.json
params:
- dvclive/params.yaml
