stages:
  data_ingestion:
    cmd: python src/datas/data_ingestion.py

    deps:
    - data/external
    - src/datas/data_ingestion.py
    params:
    - Data_ingestion.test_size

    outs:
    - data/raw
  data_preprocessing:
    cmd: python src/datas/data_preprocessing.py
    deps:
    - data/raw
    - src/datas/data_preprocessing.py
    outs:
    - data/interim
    - models/scaler.pkl
